# Generated by Django 5.2.5 on 2025-08-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfamiliares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiares',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
