# Generated by Django 5.2.5 on 2025-08-22 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfamiliares', '0002_familiares_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiares',
            name='email',
        ),
    ]
